In [1]:
# Cell 1 — Install Dependencies
!pip install transformers datasets seqeval pandas numpy matplotlib seaborn scikit-learn scispacy
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.3/en_core_sci_md-0.5.3.tar.gz

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scispacy
  Downloading scispacy-0.6.2-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.16.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: spacy<3.9.0,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from scispacy) (3.8.14)
Collecting conllu (from scispacy)
  Downloading conllu-6.0.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.8 MB/s eta 0:00:00
Collecting nmslib-metabrainz==2.1.3 (from scispacy)
  Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (956 bytes)
Collecting pysbd (from scispacy)
  Downloading pysbd-0.3.4-py3-none-any.whl.metadata (6.1 kB)
Collecting pybind11>=2.2.3 (from nmslib-metabrainz==2.1.3->scispacy)
  Downloading pybind11-3.0.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from nmslib-metabrainz==2.1.3->scispacy) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.5.20)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.3.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (75.2.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy<3.9.0,>=3.7.0->scispacy) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.4.2)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy<3.9.0,>=3.7.0->scispacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (7.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<3.9.0,>=3.7.0->scispacy) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (2.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading scispacy-0.6.2-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.9 MB/s eta 0:00:00
Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 96.2 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 104.5 MB/s eta 0:00:00
Downloading conllu-6.0.0-py3-none-any.whl (16 kB)
Downloading pysbd-0.3.4-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.1/71.1 kB 6.7 MB/s eta 0:00:00
Downloading pybind11-3.0.4-py3-none-any.whl (314 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.2/314.2 kB 34.2 MB/s eta 0:00:00
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=dff3994c88f01f464ec120154f67960a80be8b098ea98dd6fa2a7f70c08b85c5
  Stored in directory: /root/.cache/pip/wheels/5f/b8/73/0b2c1a76b701a677653dd79ece07cfabd7457989dbfbdcd8d7
Successfully built seqeval
Installing collected packages: pysbd, pybind11, numpy, conllu, nmslib-metabrainz, seqeval, scispacy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed conllu-6.0.0 nmslib-metabrainz-2.1.3 numpy-1.26.4 pybind11-3.0.4 pysbd-0.3.4 scispacy-0.6.2 seqeval-1.2.2

Collecting https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.3/en_core_sci_md-0.5.3.tar.gz
  Downloading https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.3/en_core_sci_md-0.5.3.tar.gz (119.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.1/119.1 MB 9.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting spacy<3.7.0,>=3.6.1 (from en_core_sci_md==0.5.3)
  Downloading spacy-3.6.1.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 11.7 MB/s eta 0:00:00
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [1]:
# Cell 2 — Imports
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import seaborn as sns
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score
)
import torch
import warnings
warnings.filterwarnings('ignore')

# Create output folders
os.makedirs("results/metrics", exist_ok=True)
os.makedirs("results/plots", exist_ok=True)
os.makedirs("results/models", exist_ok=True)

print("All imports successful")
print(f"GPU available: {torch.cuda.is_available()}")

ModuleNotFoundError: No module named 'seqeval'

In [1]:
!pip install seqeval -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done

In [2]:
!pip install scispacy -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 41.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 80.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.1/71.1 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.2/314.2 kB 31.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.

In [3]:
# Cell 2 — Imports
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import seaborn as sns
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score
)
import torch
import warnings
warnings.filterwarnings('ignore')

# Create output folders
os.makedirs("results/metrics", exist_ok=True)
os.makedirs("results/plots", exist_ok=True)
os.makedirs("results/models", exist_ok=True)

print("All imports successful")
print(f"GPU available: {torch.cuda.is_available()}")

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [4]:
!pip install numpy==2.0.0 -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.0/19.0 MB 78.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scispacy 0.6.2 requires numpy<2.0, but you have numpy 2.0.0 which is incompatible.

In [ ]:
import os
os.kill(os.getpid(), 9)

In [1]:
# Cell 2 — Imports
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import seaborn as sns
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score
)
import torch
import warnings
warnings.filterwarnings('ignore')

# Create output folders
os.makedirs("results/metrics", exist_ok=True)
os.makedirs("results/plots", exist_ok=True)
os.makedirs("results/models", exist_ok=True)

print("All imports successful")
print(f"GPU available: {torch.cuda.is_available()}")

All imports successful
GPU available: True

In [2]:
# Cell 3 — Load BC5CDR Dataset
print("Loading BC5CDR dataset...")
dataset = load_dataset("tner/bc5cdr")

print("\nDataset structure:")
print(dataset)

print("\nFirst training example:")
print(dataset['train'][0])

print("\nLabel list:")
label_list = dataset['train'].features['tags'].feature.names
print(label_list)

# Dataset stats
print(f"\nTraining samples: {len(dataset['train'])}")
print(f"Validation samples: {len(dataset['validation'])}")
print(f"Test samples: {len(dataset['test'])}")

Loading BC5CDR dataset...

README.md:   0%|          | 0.00/2.09k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

bc5cdr.py:   0%|          | 0.00/2.77k [00:00<?, ?B/s]

RuntimeError: Dataset scripts are no longer supported, but found bc5cdr.py

In [3]:
# Cell 3 — Load BC5CDR Dataset (updated loader)
print("Loading BC5CDR dataset...")
dataset = load_dataset("tner/bc5cdr", trust_remote_code=False)

print("\nDataset structure:")
print(dataset)

print("\nFirst training example:")
print(dataset['train'][0])

print("\nLabel list:")
label_list = dataset['train'].features['tags'].feature.names
print(label_list)

# Dataset stats
print(f"\nTraining samples:    {len(dataset['train'])}")
print(f"Validation samples:  {len(dataset['validation'])}")
print(f"Test samples:        {len(dataset['test'])}")

Loading BC5CDR dataset...

RuntimeError: Dataset scripts are no longer supported, but found bc5cdr.py

In [4]:
# Cell 3 — Load BC5CDR Dataset (alternative source)
print("Loading BC5CDR dataset...")
dataset = load_dataset("ncats/bc5cdr")

print("\nDataset structure:")
print(dataset)

print("\nFirst training example:")
print(dataset['train'][0])

print("\nLabel list:")
label_list = dataset['train'].features['tags'].feature.names
print(label_list)

# Dataset stats
print(f"\nTraining samples:    {len(dataset['train'])}")
print(f"Validation samples:  {len(dataset['validation'])}")
print(f"Test samples:        {len(dataset['test'])}")

Loading BC5CDR dataset...

DatasetNotFoundError: Dataset 'ncats/bc5cdr' doesn't exist on the Hub or cannot be accessed.

In [5]:
# Cell 3 — Load NER Dataset (using conll2003 + bio medical alternative)
print("Loading dataset...")

# Using bigbio version of BC5CDR which works with new datasets library
dataset = load_dataset("bigbio/bc5cdr", "bc5cdr_bigbio_ner", trust_remote_code=True)

print("\nDataset structure:")
print(dataset)

print("\nFirst training example:")
print(dataset['train'][0])

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'bigbio/bc5cdr' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
ERROR:datasets.load:`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'bigbio/bc5cdr' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

Loading dataset...

README.md:   0%|          | 0.00/1.68k [00:00<?, ?B/s]

bc5cdr.py:   0%|          | 0.00/13.9k [00:00<?, ?B/s]

RuntimeError: Dataset scripts are no longer supported, but found bc5cdr.py

In [6]:
# Cell 3 — Load NCBI Disease Dataset (perfect BC5CDR alternative)
print("Loading NCBI Disease NER dataset...")

dataset = load_dataset("ncbi_disease")

print("\nDataset structure:")
print(dataset)

print("\nFirst training example:")
print(dataset['train'][0])

print("\nLabel list:")
label_list = dataset['train'].features['ner_tags'].feature.names
print(label_list)

# Dataset stats
print(f"\nTraining samples:    {len(dataset['train'])}")
print(f"Validation samples:  {len(dataset['validation'])}")
print(f"Test samples:        {len(dataset['test'])}")

Loading NCBI Disease NER dataset...

README.md:   0%|          | 0.00/9.70k [00:00<?, ?B/s]

ncbi_disease.py:   0%|          | 0.00/5.83k [00:00<?, ?B/s]

RuntimeError: Dataset scripts are no longer supported, but found ncbi_disease.py

In [7]:
# Cell 3 — Load dataset from HuggingFace (most stable version)
print("Loading dataset...")

dataset = load_dataset("drAbreu/bioBERT-NER-BC5CDR_disease")

print("\nDataset loaded successfully")
print(dataset)

Loading dataset...

DatasetNotFoundError: Dataset 'drAbreu/bioBERT-NER-BC5CDR_disease' doesn't exist on the Hub or cannot be accessed.

In [8]:
# Download BC5CDR dataset directly
!pip install huggingface_hub -q

from huggingface_hub import hf_hub_download
import os

os.makedirs("data", exist_ok=True)

# Download directly from HuggingFace
!wget -q "https://raw.githubusercontent.com/cambridgeltl/MTL-Bioinformatics-2016/master/data/BC5CDR-chem-IOB/train.tsv" -O "data/train.tsv"
!wget -q "https://raw.githubusercontent.com/cambridgeltl/MTL-Bioinformatics-2016/master/data/BC5CDR-chem-IOB/devel.tsv" -O "data/val.tsv"
!wget -q "https://raw.githubusercontent.com/cambridgeltl/MTL-Bioinformatics-2016/master/data/BC5CDR-chem-IOB/test.tsv" -O "data/test.tsv"

# Check files downloaded
print("Files downloaded:")
for f in ['data/train.tsv', 'data/val.tsv', 'data/test.tsv']:
    if os.path.exists(f):
        print(f"  ✅ {f} — {os.path.getsize(f)} bytes")
    else:
        print(f"  ❌ {f} — NOT FOUND")

Files downloaded:
  ✅ data/train.tsv — 983140 bytes
  ✅ data/val.tsv — 976029 bytes
  ✅ data/test.tsv — 1023429 bytes

In [9]:
# Cell 3 — Load BC5CDR from downloaded files
print("Loading BC5CDR dataset from local files...")

def read_conll_file(filepath):
    sentences = []
    tokens = []
    tags = []

    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line == "" or line.startswith("-DOCSTART-"):
                if tokens:
                    sentences.append({
                        'tokens': tokens,
                        'tags': tags
                    })
                    tokens = []
                    tags = []
            else:
                parts = line.split('\t')
                if len(parts) >= 2:
                    tokens.append(parts[0])
                    tags.append(parts[-1])

    if tokens:
        sentences.append({'tokens': tokens, 'tags': tags})

    return sentences

# Load all splits
train_data = read_conll_file('data/train.tsv')
val_data   = read_conll_file('data/val.tsv')
test_data  = read_conll_file('data/test.tsv')

print(f"✅ Training samples:   {len(train_data)}")
print(f"✅ Validation samples: {len(val_data)}")
print(f"✅ Test samples:       {len(test_data)}")

print("\nFirst training example:")
print(train_data[0])

# Get all unique labels
all_tags = set()
for item in train_data + val_data + test_data:
    all_tags.update(item['tags'])

label_list = sorted(list(all_tags))
print(f"\nLabel list: {label_list}")

label2id = {l: i for i, l in enumerate(label_list)}
id2label  = {i: l for i, l in enumerate(label_list)}
print(f"\nLabel mapping: {label2id}")

Loading BC5CDR dataset from local files...
✅ Training samples:   4560
✅ Validation samples: 4581
✅ Test samples:       4797

First training example:
{'tokens': ['Selegiline', '-', 'induced', 'postural', 'hypotension', 'in', 'Parkinson', "'", 's', 'disease', ':', 'a', 'longitudinal', 'study', 'on', 'the', 'effects', 'of', 'drug', 'withdrawal', '.'], 'tags': ['B-Chemical', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']}

Label list: ['B-Chemical', 'I-Chemical', 'O']

Label mapping: {'B-Chemical': 0, 'I-Chemical': 1, 'O': 2}

In [10]:
# Cell 3b — Convert to HuggingFace Dataset format
from datasets import Dataset, DatasetDict

def convert_to_hf_dataset(data, label2id):
    converted = {
        'tokens': [],
        'tags': []
    }
    for item in data:
        converted['tokens'].append(item['tokens'])
        converted['tags'].append([label2id[t] for t in item['tags']])
    return Dataset.from_dict(converted)

dataset = DatasetDict({
    'train':      convert_to_hf_dataset(train_data, label2id),
    'validation': convert_to_hf_dataset(val_data, label2id),
    'test':       convert_to_hf_dataset(test_data, label2id)
})

print("Dataset converted successfully:")
print(dataset)
print("\nFirst example:")
print(dataset['train'][0])

Dataset converted successfully:
DatasetDict({
    train: Dataset({
        features: ['tokens', 'tags'],
        num_rows: 4560
    })
    validation: Dataset({
        features: ['tokens', 'tags'],
        num_rows: 4581
    })
    test: Dataset({
        features: ['tokens', 'tags'],
        num_rows: 4797
    })
})

First example:
{'tokens': ['Selegiline', '-', 'induced', 'postural', 'hypotension', 'in', 'Parkinson', "'", 's', 'disease', ':', 'a', 'longitudinal', 'study', 'on', 'the', 'effects', 'of', 'drug', 'withdrawal', '.'], 'tags': [0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

In [11]:
# Cell 5 — Tokenization
label_list = dataset['train'].features['tags'].feature.names
label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for i, l in enumerate(label_list)}

def tokenize_and_align_labels(examples, tokenizer, max_length=128):
    tokenized = tokenizer(
        examples['tokens'],
        truncation=True,
        is_split_into_words=True,
        max_length=max_length,
        padding='max_length'
    )

    all_labels = []
    for i, tags in enumerate(examples['tags']):
        word_ids = tokenized.word_ids(batch_index=i)
        label_ids = []
        prev_word_id = None
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word_id:
                label_ids.append(tags[word_id])
            else:
                label_ids.append(-100)
            prev_word_id = word_id
        all_labels.append(label_ids)

    tokenized['labels'] = all_labels
    return tokenized

print("Tokenization function ready")

AttributeError: 'Value' object has no attribute 'names'

In [1]:
# Cell 4 — Dataset Visualization (updated for manual dataset)
from collections import Counter
import matplotlib.pyplot as plt

# Count label frequencies from our manually loaded data
all_labels = []
for example in train_data:
    all_labels.extend(example['tags'])

label_counts = Counter(all_labels)

# Sort by frequency
sorted_labels = sorted(label_counts.items(), key=lambda x: x[1], reverse=True)
label_names = [item[0] for item in sorted_labels]
label_values = [item[1] for item in sorted_labels]

# Plot
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('BC5CDR Dataset Analysis', fontsize=14, fontweight='bold')

# Plot 1 — Label distribution bar chart
colors = ['#FF6B6B' if 'B-' in l or 'I-' in l else '#4ECDC4' for l in label_names]
bars = axes[0].bar(label_names, label_values, color=colors,
                   edgecolor='white', linewidth=0.5)
axes[0].set_title('Label Distribution — Training Set', fontweight='bold')
axes[0].set_xlabel('Entity Labels')
axes[0].set_ylabel('Frequency')
axes[0].tick_params(axis='x', rotation=45)

for bar, val in zip(bars, label_values):
    axes[0].text(bar.get_x() + bar.get_width()/2., bar.get_height() + 50,
                 f'{val:,}', ha='center', va='bottom', fontsize=9)

# Plot 2 — Dataset split sizes
split_names = ['Train', 'Validation', 'Test']
split_sizes = [len(train_data), len(val_data), len(test_data)]
split_colors = ['#FF6B6B', '#4ECDC4', '#45B7D1']

bars2 = axes[1].bar(split_names, split_sizes, color=split_colors,
                    edgecolor='white', linewidth=0.5, width=0.4)
axes[1].set_title('Dataset Split Sizes', fontweight='bold')
axes[1].set_xlabel('Split')
axes[1].set_ylabel('Number of Sentences')

for bar, val in zip(bars2, split_sizes):
    axes[1].text(bar.get_x() + bar.get_width()/2., bar.get_height() + 5,
                 f'{val:,}', ha='center', va='bottom',
                 fontsize=11, fontweight='bold')

plt.tight_layout()
os.makedirs("results/plots", exist_ok=True)
plt.savefig('results/plots/dataset_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Plot saved to results/plots/dataset_distribution.png")

# Print summary stats
print(f"\nDataset Summary:")
print(f"  Training sentences:   {len(train_data):,}")
print(f"  Validation sentences: {len(val_data):,}")
print(f"  Test sentences:       {len(test_data):,}")
print(f"  Total labels:         {len(label_list)}")
print(f"  Label types:          {label_names}")

NameError: name 'train_data' is not defined

In [2]:
# Cell 1 — Install Dependencies
# Run this ONLY once at the start

!pip install numpy==2.0.0 -q
!pip install transformers datasets seqeval matplotlib seaborn scikit-learn -q
!pip install scispacy -q
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.3/en_core_sci_md-0.5.3.tar.gz -q

print("✅ All packages installed")
print("⚠️  Now go to Runtime → Restart Session, then run from Cell 2")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.0/19.0 MB 96.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 94.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 74.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.1/71.1 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.2/314.2 kB 32.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.1/119.1 MB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 70.3 MB/s eta 0:00:00
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
✅ All packages installed
⚠️  Now go to Runtime → Restart Session, then run from Cell 2

In [1]:
# Cell 2 — Imports
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import seaborn as sns
from collections import Counter
from datasets import Dataset, DatasetDict, load_from_disk
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score
)
import torch
import warnings
warnings.filterwarnings('ignore')

# Create all folders
os.makedirs("results/metrics", exist_ok=True)
os.makedirs("results/plots", exist_ok=True)
os.makedirs("results/models", exist_ok=True)
os.makedirs("data", exist_ok=True)

print("✅ All imports successful")
print(f"✅ GPU available: {torch.cuda.is_available()}")

✅ All imports successful
✅ GPU available: True

In [2]:
# Cell 3 — Download Dataset
# Only downloads if files don't exist already

def download_dataset():
    files = {
        'data/train.tsv': 'https://raw.githubusercontent.com/cambridgeltl/MTL-Bioinformatics-2016/master/data/BC5CDR-chem-IOB/train.tsv',
        'data/val.tsv':   'https://raw.githubusercontent.com/cambridgeltl/MTL-Bioinformatics-2016/master/data/BC5CDR-chem-IOB/devel.tsv',
        'data/test.tsv':  'https://raw.githubusercontent.com/cambridgeltl/MTL-Bioinformatics-2016/master/data/BC5CDR-chem-IOB/test.tsv'
    }

    all_exist = all(os.path.exists(f) and os.path.getsize(f) > 0
                    for f in files.keys())

    if all_exist:
        print("✅ Dataset files already exist — skipping download")
        return

    print("Downloading BC5CDR dataset...")
    for local_path, url in files.items():
        os.system(f'wget -q "{url}" -O "{local_path}"')
        size = os.path.getsize(local_path) if os.path.exists(local_path) else 0
        status = "✅" if size > 0 else "❌"
        print(f"{status} {local_path} — {size:,} bytes")

download_dataset()

Downloading BC5CDR dataset...
✅ data/train.tsv — 983,140 bytes
✅ data/val.tsv — 976,029 bytes
✅ data/test.tsv — 1,023,429 bytes

In [3]:
# Cell 4 — Load and Parse Dataset
# Auto-reloads from disk if runtime restarted

def read_conll_file(filepath):
    sentences = []
    tokens = []
    tags = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line == "" or line.startswith("-DOCSTART-"):
                if tokens:
                    sentences.append({'tokens': tokens, 'tags': tags})
                    tokens = []
                    tags = []
            else:
                parts = line.split('\t')
                if len(parts) >= 2:
                    tokens.append(parts[0])
                    tags.append(parts[-1])
    if tokens:
        sentences.append({'tokens': tokens, 'tags': tags})
    return sentences

# Check if processed dataset already saved on disk
DATASET_SAVED = os.path.exists("data/bc5cdr_dataset") and \
                os.path.exists("data/label_info.json")

if DATASET_SAVED:
    print("✅ Processed dataset found on disk — loading...")
    dataset   = load_from_disk("data/bc5cdr_dataset")
    train_data = read_conll_file('data/train.tsv')
    val_data   = read_conll_file('data/val.tsv')
    test_data  = read_conll_file('data/test.tsv')

    with open("data/label_info.json", "r") as f:
        label_info = json.load(f)
    label_list = label_info['label_list']
    label2id   = label_info['label2id']
    id2label   = {int(k): v for k, v in label_info['id2label'].items()}
    print("✅ Dataset reloaded successfully")

else:
    print("Processing dataset for first time...")
    train_data = read_conll_file('data/train.tsv')
    val_data   = read_conll_file('data/val.tsv')
    test_data  = read_conll_file('data/test.tsv')

    # Build label list
    all_tags = set()
    for item in train_data + val_data + test_data:
        all_tags.update(item['tags'])
    label_list = sorted(list(all_tags))
    label2id   = {l: i for i, l in enumerate(label_list)}
    id2label   = {i: l for i, l in enumerate(label_list)}

    # Convert to HuggingFace Dataset
    def convert_to_hf(data):
        return Dataset.from_dict({
            'tokens': [d['tokens'] for d in data],
            'tags':   [[label2id[t] for t in d['tags']] for d in data]
        })

    dataset = DatasetDict({
        'train':      convert_to_hf(train_data),
        'validation': convert_to_hf(val_data),
        'test':       convert_to_hf(test_data)
    })

    # Save everything to disk
    dataset.save_to_disk("data/bc5cdr_dataset")
    with open("data/label_info.json", "w") as f:
        json.dump({
            "label_list": label_list,
            "label2id":   label2id,
            "id2label":   id2label
        }, f)
    print("✅ Dataset processed and saved to disk")

print(f"\n✅ Train:      {len(train_data):,} sentences")
print(f"✅ Validation: {len(val_data):,} sentences")
print(f"✅ Test:       {len(test_data):,} sentences")
print(f"✅ Labels:     {label_list}")
print(f"\nFirst example: {dataset['train'][0]}")

Processing dataset for first time...

Saving the dataset (0/1 shards):   0%|          | 0/4560 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/4581 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/4797 [00:00<?, ? examples/s]

✅ Dataset processed and saved to disk

✅ Train:      4,560 sentences
✅ Validation: 4,581 sentences
✅ Test:       4,797 sentences
✅ Labels:     ['B-Chemical', 'I-Chemical', 'O']

First example: {'tokens': ['Selegiline', '-', 'induced', 'postural', 'hypotension', 'in', 'Parkinson', "'", 's', 'disease', ':', 'a', 'longitudinal', 'study', 'on', 'the', 'effects', 'of', 'drug', 'withdrawal', '.'], 'tags': [0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

In [4]:
# Cell 5 — Dataset Visualization

all_labels = []
for example in train_data:
    all_labels.extend(example['tags'])

label_counts  = Counter(all_labels)
sorted_labels = sorted(label_counts.items(), key=lambda x: x[1], reverse=True)
label_names   = [item[0] for item in sorted_labels]
label_values  = [item[1] for item in sorted_labels]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('BC5CDR Dataset Analysis', fontsize=14, fontweight='bold')

# Plot 1 — Label distribution
colors = ['#FF6B6B' if 'B-' in l or 'I-' in l else '#4ECDC4' for l in label_names]
bars = axes[0].bar(label_names, label_values, color=colors,
                   edgecolor='white', linewidth=0.5)
axes[0].set_title('Label Distribution — Training Set', fontweight='bold')
axes[0].set_xlabel('Entity Labels')
axes[0].set_ylabel('Frequency')
axes[0].tick_params(axis='x', rotation=45)
for bar, val in zip(bars, label_values):
    axes[0].text(bar.get_x() + bar.get_width()/2.,
                 bar.get_height() + 50,
                 f'{val:,}', ha='center', va='bottom', fontsize=9)

# Plot 2 — Split sizes
split_names  = ['Train', 'Validation', 'Test']
split_sizes  = [len(train_data), len(val_data), len(test_data)]
split_colors = ['#FF6B6B', '#4ECDC4', '#45B7D1']
bars2 = axes[1].bar(split_names, split_sizes, color=split_colors,
                    edgecolor='white', linewidth=0.5, width=0.4)
axes[1].set_title('Dataset Split Sizes', fontweight='bold')
axes[1].set_xlabel('Split')
axes[1].set_ylabel('Number of Sentences')
for bar, val in zip(bars2, split_sizes):
    axes[1].text(bar.get_x() + bar.get_width()/2.,
                 bar.get_height() + 5,
                 f'{val:,}', ha='center', va='bottom',
                 fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('results/plots/dataset_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Plot saved to results/plots/dataset_distribution.png")

✅ Plot saved to results/plots/dataset_distribution.png

In [5]:
# Cell 6 — Tokenization Function

def tokenize_and_align_labels(examples, tokenizer, max_length=128):
    tokenized = tokenizer(
        examples['tokens'],
        truncation=True,
        is_split_into_words=True,
        max_length=max_length,
        padding='max_length'
    )
    all_labels = []
    for i, tags in enumerate(examples['tags']):
        word_ids  = tokenized.word_ids(batch_index=i)
        label_ids = []
        prev_word_id = None
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word_id:
                label_ids.append(tags[word_id])
            else:
                label_ids.append(-100)
            prev_word_id = word_id
        all_labels.append(label_ids)
    tokenized['labels'] = all_labels
    return tokenized

print("✅ Tokenization function ready")

✅ Tokenization function ready

In [6]:
# Cell 7 — Evaluation Function

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=2)
    true_labels = [
        [id2label[l] for l in label_row if l != -100]
        for label_row in labels
    ]
    true_predictions = [
        [id2label[p] for p, l in zip(pred_row, label_row) if l != -100]
        for pred_row, label_row in zip(predictions, labels)
    ]
    return {
        "precision": precision_score(true_labels, true_predictions),
        "recall":    recall_score(true_labels, true_predictions),
        "f1":        f1_score(true_labels, true_predictions),
    }

print("✅ Evaluation function ready")

✅ Evaluation function ready

In [7]:
# Cell 8 — Training Function

def train_model(model_name, display_name, epochs=3):
    print(f"\n{'='*60}")
    print(f"Training: {display_name}")
    print(f"Model:    {model_name}")
    print(f"{'='*60}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    tokenized_dataset = dataset.map(
        lambda x: tokenize_and_align_labels(x, tokenizer),
        batched=True,
        remove_columns=dataset['train'].column_names
    )

    model = AutoModelForTokenClassification.from_pretrained(
        model_name,
        num_labels=len(label_list),
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True
    )

    safe_name = display_name.replace(" ", "_")
    training_args = TrainingArguments(
        output_dir=f"results/models/{safe_name}",
        num_train_epochs=epochs,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_steps=50,
        fp16=torch.cuda.is_available(),
        report_to="none"
    )

    data_collator = DataCollatorForTokenClassification(tokenizer)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset['train'],
        eval_dataset=tokenized_dataset['validation'],
        tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )

    print(f"\nStarting training...")
    train_result = trainer.train()

    print(f"\nEvaluating on test set...")
    test_results = trainer.evaluate(tokenized_dataset['test'])

    # Detailed predictions
    predictions  = trainer.predict(tokenized_dataset['test'])
    preds        = np.argmax(predictions.predictions, axis=2)
    true_labels_list = [
        [id2label[l] for l in row if l != -100]
        for row in predictions.label_ids
    ]
    pred_labels_list = [
        [id2label[p] for p, l in zip(pr, lr) if l != -100]
        for pr, lr in zip(preds, predictions.label_ids)
    ]
    report = classification_report(
        true_labels_list, pred_labels_list, output_dict=True
    )

    results = {
        'model_name':            display_name,
        'precision':             test_results.get('eval_precision', 0),
        'recall':                test_results.get('eval_recall', 0),
        'f1':                    test_results.get('eval_f1', 0),
        'classification_report': report,
        'history':               trainer.state.log_history,
        'training_time':         train_result.metrics['train_runtime']
    }

    print(f"\n✅ {display_name} Results:")
    print(f"   Precision : {results['precision']:.4f}")
    print(f"   Recall    : {results['recall']:.4f}")
    print(f"   F1 Score  : {results['f1']:.4f}")

    return results, trainer, tokenizer

print("✅ Training function ready")

✅ Training function ready

In [8]:
# Cell 9 — Train All 3 Models
# This takes 2-3 hours — do not close Colab

all_results = {}

# ── Model 1: BioBERT ──────────────────────────────────────
results_biobert, trainer_biobert, tok_biobert = train_model(
    "dmis-lab/biobert-base-cased-v1.2", "BioBERT"
)
all_results['BioBERT'] = results_biobert
with open('results/metrics/biobert_results.json', 'w') as f:
    json.dump({k: v for k, v in results_biobert.items()
               if k not in ['classification_report', 'history']}, f, indent=2)
print("✅ BioBERT results saved")

# ── Model 2: PubMedBERT ───────────────────────────────────
results_pubmed, trainer_pubmed, tok_pubmed = train_model(
    "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext",
    "PubMedBERT"
)
all_results['PubMedBERT'] = results_pubmed
with open('results/metrics/pubmedbert_results.json', 'w') as f:
    json.dump({k: v for k, v in results_pubmed.items()
               if k not in ['classification_report', 'history']}, f, indent=2)
print("✅ PubMedBERT results saved")

# ── Model 3: spaCy Medical ────────────────────────────────
import spacy
print("\nEvaluating spaCy Medical model...")
nlp_sci = spacy.load("en_core_sci_md")

spacy_preds = []
spacy_true  = []

for example in dataset['test'].select(range(200)):
    tokens    = example['tokens']
    true_tags = [id2label[t] for t in example['tags']]
    text      = " ".join(tokens)
    doc       = nlp_sci(text)

    pred_tags  = ['O'] * len(tokens)
    char_count = 0
    for ent in doc.ents:
        for i, token in enumerate(tokens):
            token_start = sum(len(t) + 1 for t in tokens[:i])
            if token_start >= ent.start_char and token_start < ent.end_char:
                pred_tags[i] = 'B-Chemical' if ent.label_ == 'CHEMICAL' \
                                else 'B-Disease'

    spacy_preds.append(pred_tags)
    spacy_true.append(true_tags)

spacy_f1        = f1_score(spacy_true, spacy_preds)
spacy_precision = precision_score(spacy_true, spacy_preds)
spacy_recall    = recall_score(spacy_true, spacy_preds)

all_results['spaCy Medical'] = {
    'model_name':    'spaCy Medical',
    'precision':     spacy_precision,
    'recall':        spacy_recall,
    'f1':            spacy_f1,
    'training_time': 0
}

with open('results/metrics/spacy_results.json', 'w') as f:
    json.dump(all_results['spaCy Medical'], f, indent=2)

print(f"\n✅ spaCy Medical Results:")
print(f"   Precision : {spacy_precision:.4f}")
print(f"   Recall    : {spacy_recall:.4f}")
print(f"   F1 Score  : {spacy_f1:.4f}")

print("\n✅ All 3 models done")

============================================================
Training: BioBERT
Model:    dmis-lab/biobert-base-cased-v1.2
============================================================

config.json:   0%|          | 0.00/1.11k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

Map:   0%|          | 0/4560 [00:00<?, ? examples/s]

Map:   0%|          | 0/4581 [00:00<?, ? examples/s]

Map:   0%|          | 0/4797 [00:00<?, ? examples/s]

pytorch_model.bin:   0%|          | 0.00/436M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

BertForTokenClassification LOAD REPORT from: dmis-lab/biobert-base-cased-v1.2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

TypeError: Trainer.__init__() got an unexpected keyword argument 'tokenizer'

In [9]:
# Cell 8 — Training Function (updated for new transformers version)

def train_model(model_name, display_name, epochs=3):
    print(f"\n{'='*60}")
    print(f"Training: {display_name}")
    print(f"Model:    {model_name}")
    print(f"{'='*60}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    tokenized_dataset = dataset.map(
        lambda x: tokenize_and_align_labels(x, tokenizer),
        batched=True,
        remove_columns=dataset['train'].column_names
    )

    model = AutoModelForTokenClassification.from_pretrained(
        model_name,
        num_labels=len(label_list),
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True
    )

    safe_name = display_name.replace(" ", "_")
    training_args = TrainingArguments(
        output_dir=f"results/models/{safe_name}",
        num_train_epochs=epochs,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_steps=50,
        fp16=torch.cuda.is_available(),
        report_to="none"
    )

    data_collator = DataCollatorForTokenClassification(tokenizer)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset['train'],
        eval_dataset=tokenized_dataset['validation'],
        processing_class=tokenizer,        # ← updated from 'tokenizer'
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )

    print(f"\nStarting training...")
    train_result = trainer.train()

    print(f"\nEvaluating on test set...")
    test_results = trainer.evaluate(tokenized_dataset['test'])

    # Detailed predictions
    predictions      = trainer.predict(tokenized_dataset['test'])
    preds            = np.argmax(predictions.predictions, axis=2)
    true_labels_list = [
        [id2label[l] for l in row if l != -100]
        for row in predictions.label_ids
    ]
    pred_labels_list = [
        [id2label[p] for p, l in zip(pr, lr) if l != -100]
        for pr, lr in zip(preds, predictions.label_ids)
    ]
    report = classification_report(
        true_labels_list, pred_labels_list, output_dict=True
    )

    results = {
        'model_name':            display_name,
        'precision':             test_results.get('eval_precision', 0),
        'recall':                test_results.get('eval_recall', 0),
        'f1':                    test_results.get('eval_f1', 0),
        'classification_report': report,
        'history':               trainer.state.log_history,
        'training_time':         train_result.metrics['train_runtime']
    }

    print(f"\n✅ {display_name} Results:")
    print(f"   Precision : {results['precision']:.4f}")
    print(f"   Recall    : {results['recall']:.4f}")
    print(f"   F1 Score  : {results['f1']:.4f}")

    return results, trainer, tokenizer

print("✅ Training function ready")

✅ Training function ready

In [10]:
# Cell 9 — Train All 3 Models
# This takes 2-3 hours — do not close Colab

all_results = {}

# ── Model 1: BioBERT ──────────────────────────────────────
results_biobert, trainer_biobert, tok_biobert = train_model(
    "dmis-lab/biobert-base-cased-v1.2", "BioBERT"
)
all_results['BioBERT'] = results_biobert
with open('results/metrics/biobert_results.json', 'w') as f:
    json.dump({k: v for k, v in results_biobert.items()
               if k not in ['classification_report', 'history']}, f, indent=2)
print("✅ BioBERT results saved")

# ── Model 2: PubMedBERT ───────────────────────────────────
results_pubmed, trainer_pubmed, tok_pubmed = train_model(
    "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext",
    "PubMedBERT"
)
all_results['PubMedBERT'] = results_pubmed
with open('results/metrics/pubmedbert_results.json', 'w') as f:
    json.dump({k: v for k, v in results_pubmed.items()
               if k not in ['classification_report', 'history']}, f, indent=2)
print("✅ PubMedBERT results saved")

# ── Model 3: spaCy Medical ────────────────────────────────
import spacy
print("\nEvaluating spaCy Medical model...")
nlp_sci = spacy.load("en_core_sci_md")

spacy_preds = []
spacy_true  = []

for example in dataset['test'].select(range(200)):
    tokens    = example['tokens']
    true_tags = [id2label[t] for t in example['tags']]
    text      = " ".join(tokens)
    doc       = nlp_sci(text)

    pred_tags  = ['O'] * len(tokens)
    char_count = 0
    for ent in doc.ents:
        for i, token in enumerate(tokens):
            token_start = sum(len(t) + 1 for t in tokens[:i])
            if token_start >= ent.start_char and token_start < ent.end_char:
                pred_tags[i] = 'B-Chemical' if ent.label_ == 'CHEMICAL' \
                                else 'B-Disease'

    spacy_preds.append(pred_tags)
    spacy_true.append(true_tags)

spacy_f1        = f1_score(spacy_true, spacy_preds)
spacy_precision = precision_score(spacy_true, spacy_preds)
spacy_recall    = recall_score(spacy_true, spacy_preds)

all_results['spaCy Medical'] = {
    'model_name':    'spaCy Medical',
    'precision':     spacy_precision,
    'recall':        spacy_recall,
    'f1':            spacy_f1,
    'training_time': 0
}

with open('results/metrics/spacy_results.json', 'w') as f:
    json.dump(all_results['spaCy Medical'], f, indent=2)

print(f"\n✅ spaCy Medical Results:")
print(f"   Precision : {spacy_precision:.4f}")
print(f"   Recall    : {spacy_recall:.4f}")
print(f"   F1 Score  : {spacy_f1:.4f}")

print("\n✅ All 3 models done")

============================================================
Training: BioBERT
Model:    dmis-lab/biobert-base-cased-v1.2
============================================================

Map:   0%|          | 0/4560 [00:00<?, ? examples/s]

Map:   0%|          | 0/4581 [00:00<?, ? examples/s]

Map:   0%|          | 0/4797 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dmis-lab/biobert-base-cased-v1.2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

Evaluating on test set...

✅ BioBERT Results:
   Precision : 0.9047
   Recall    : 0.9385
   F1 Score  : 0.9213
✅ BioBERT results saved

============================================================
Training: PubMedBERT
Model:    microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
============================================================

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/226k [00:00<?, ?B/s]

Map:   0%|          | 0/4560 [00:00<?, ? examples/s]

Map:   0%|          | 0/4581 [00:00<?, ? examples/s]

Map:   0%|          | 0/4797 [00:00<?, ? examples/s]

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Starting training...

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

Evaluating on test set...

✅ PubMedBERT Results:
   Precision : 0.9137
   Recall    : 0.9361
   F1 Score  : 0.9248
✅ PubMedBERT results saved

Evaluating spaCy Medical model...

OSError: [E050] Can't find model 'en_core_sci_md'. It doesn't seem to be a Python package or a valid path to a data directory.

In [11]:
print(all_results.keys())

dict_keys(['BioBERT', 'PubMedBERT'])

In [12]:
# Cell 9b — spaCy evaluation only (run this, not full Cell 9)
import spacy
import os

# Install spaCy medical model
print("Installing spaCy medical model...")
os.system("pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.3/en_core_sci_md-0.5.3.tar.gz -q")

# Load model
import en_core_sci_md
nlp_sci = en_core_sci_md.load()
print("✅ spaCy medical model loaded")

spacy_preds = []
spacy_true  = []

for example in dataset['test'].select(range(200)):
    tokens    = example['tokens']
    true_tags = [id2label[t] for t in example['tags']]
    text      = " ".join(tokens)
    doc       = nlp_sci(text)

    pred_tags = ['O'] * len(tokens)
    for i, token in enumerate(tokens):
        token_start = sum(len(t) + 1 for t in tokens[:i])
        for ent in doc.ents:
            if token_start >= ent.start_char and token_start < ent.end_char:
                pred_tags[i] = 'B-Chemical' if ent.label_ == 'CHEMICAL' \
                                else 'B-Disease'

    spacy_preds.append(pred_tags)
    spacy_true.append(true_tags)

spacy_f1        = f1_score(spacy_true, spacy_preds)
spacy_precision = precision_score(spacy_true, spacy_preds)
spacy_recall    = recall_score(spacy_true, spacy_preds)

all_results['spaCy Medical'] = {
    'model_name':    'spaCy Medical',
    'precision':     spacy_precision,
    'recall':        spacy_recall,
    'f1':            spacy_f1,
    'training_time': 0
}

with open('results/metrics/spacy_results.json', 'w') as f:
    json.dump(all_results['spaCy Medical'], f, indent=2)

print(f"\n✅ spaCy Medical Results:")
print(f"   Precision : {spacy_precision:.4f}")
print(f"   Recall    : {spacy_recall:.4f}")
print(f"   F1 Score  : {spacy_f1:.4f}")

print("\n✅ All 3 models done")
print(f"\nAll results keys: {list(all_results.keys())}")

Installing spaCy medical model...

ModuleNotFoundError: No module named 'en_core_sci_md'

In [13]:
# Cell 9b - Part 1 — Install spaCy model and restart
import os

print("Installing spaCy medical model...")
os.system("pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.3/en_core_sci_md-0.5.3.tar.gz -q")
print("✅ Installation done")
print("⚠️ Now restart runtime — Runtime → Restart Session")
print("⚠️ After restart run Cell 9c (do NOT run Cell 9 again)")

Installing spaCy medical model...
✅ Installation done
⚠️ Now restart runtime — Runtime → Restart Session
⚠️ After restart run Cell 9c (do NOT run Cell 9 again)

In [1]:
# Cell 2 — Imports
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import seaborn as sns
from collections import Counter
from datasets import Dataset, DatasetDict, load_from_disk
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score
)
import torch
import warnings
warnings.filterwarnings('ignore')

# Create all folders
os.makedirs("results/metrics", exist_ok=True)
os.makedirs("results/plots", exist_ok=True)
os.makedirs("results/models", exist_ok=True)
os.makedirs("data", exist_ok=True)

print("✅ All imports successful")
print(f"✅ GPU available: {torch.cuda.is_available()}")

✅ All imports successful
✅ GPU available: True

In [2]:
# Cell 4 — Load and Parse Dataset
# Auto-reloads from disk if runtime restarted

def read_conll_file(filepath):
    sentences = []
    tokens = []
    tags = []
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line == "" or line.startswith("-DOCSTART-"):
                if tokens:
                    sentences.append({'tokens': tokens, 'tags': tags})
                    tokens = []
                    tags = []
            else:
                parts = line.split('\t')
                if len(parts) >= 2:
                    tokens.append(parts[0])
                    tags.append(parts[-1])
    if tokens:
        sentences.append({'tokens': tokens, 'tags': tags})
    return sentences

# Check if processed dataset already saved on disk
DATASET_SAVED = os.path.exists("data/bc5cdr_dataset") and \
                os.path.exists("data/label_info.json")

if DATASET_SAVED:
    print("✅ Processed dataset found on disk — loading...")
    dataset   = load_from_disk("data/bc5cdr_dataset")
    train_data = read_conll_file('data/train.tsv')
    val_data   = read_conll_file('data/val.tsv')
    test_data  = read_conll_file('data/test.tsv')

    with open("data/label_info.json", "r") as f:
        label_info = json.load(f)
    label_list = label_info['label_list']
    label2id   = label_info['label2id']
    id2label   = {int(k): v for k, v in label_info['id2label'].items()}
    print("✅ Dataset reloaded successfully")

else:
    print("Processing dataset for first time...")
    train_data = read_conll_file('data/train.tsv')
    val_data   = read_conll_file('data/val.tsv')
    test_data  = read_conll_file('data/test.tsv')

    # Build label list
    all_tags = set()
    for item in train_data + val_data + test_data:
        all_tags.update(item['tags'])
    label_list = sorted(list(all_tags))
    label2id   = {l: i for i, l in enumerate(label_list)}
    id2label   = {i: l for i, l in enumerate(label_list)}

    # Convert to HuggingFace Dataset
    def convert_to_hf(data):
        return Dataset.from_dict({
            'tokens': [d['tokens'] for d in data],
            'tags':   [[label2id[t] for t in d['tags']] for d in data]
        })

    dataset = DatasetDict({
        'train':      convert_to_hf(train_data),
        'validation': convert_to_hf(val_data),
        'test':       convert_to_hf(test_data)
    })

    # Save everything to disk
    dataset.save_to_disk("data/bc5cdr_dataset")
    with open("data/label_info.json", "w") as f:
        json.dump({
            "label_list": label_list,
            "label2id":   label2id,
            "id2label":   id2label
        }, f)
    print("✅ Dataset processed and saved to disk")

print(f"\n✅ Train:      {len(train_data):,} sentences")
print(f"✅ Validation: {len(val_data):,} sentences")
print(f"✅ Test:       {len(test_data):,} sentences")
print(f"✅ Labels:     {label_list}")
print(f"\nFirst example: {dataset['train'][0]}")

✅ Processed dataset found on disk — loading...
✅ Dataset reloaded successfully

✅ Train:      4,560 sentences
✅ Validation: 4,581 sentences
✅ Test:       4,797 sentences
✅ Labels:     ['B-Chemical', 'I-Chemical', 'O']

First example: {'tokens': ['Selegiline', '-', 'induced', 'postural', 'hypotension', 'in', 'Parkinson', "'", 's', 'disease', ':', 'a', 'longitudinal', 'study', 'on', 'the', 'effects', 'of', 'drug', 'withdrawal', '.'], 'tags': [0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]}

In [3]:
# Cell 9c — Reload previous results + run spaCy evaluation

import json
import os
from seqeval.metrics import f1_score, precision_score, recall_score

# ── Reload BioBERT and PubMedBERT results from saved JSON files ──
all_results = {}

with open('results/metrics/biobert_results.json', 'r') as f:
    all_results['BioBERT'] = json.load(f)
print(f"✅ BioBERT reloaded   — F1: {all_results['BioBERT']['f1']:.4f}")

with open('results/metrics/pubmedbert_results.json', 'r') as f:
    all_results['PubMedBERT'] = json.load(f)
print(f"✅ PubMedBERT reloaded — F1: {all_results['PubMedBERT']['f1']:.4f}")

# ── spaCy evaluation ──────────────────────────────────────────────
import spacy
import en_core_sci_md
nlp_sci = en_core_sci_md.load()
print("✅ spaCy medical model loaded")

spacy_preds = []
spacy_true  = []

for example in dataset['test'].select(range(200)):
    tokens    = example['tokens']
    true_tags = [id2label[t] for t in example['tags']]
    text      = " ".join(tokens)
    doc       = nlp_sci(text)

    pred_tags = ['O'] * len(tokens)
    for i, token in enumerate(tokens):
        token_start = sum(len(t) + 1 for t in tokens[:i])
        for ent in doc.ents:
            if token_start >= ent.start_char and token_start < ent.end_char:
                pred_tags[i] = 'B-Chemical' if ent.label_ == 'CHEMICAL' \
                                else 'B-Disease'

    spacy_preds.append(pred_tags)
    spacy_true.append(true_tags)

spacy_f1        = f1_score(spacy_true, spacy_preds)
spacy_precision = precision_score(spacy_true, spacy_preds)
spacy_recall    = recall_score(spacy_true, spacy_preds)

all_results['spaCy Medical'] = {
    'model_name':    'spaCy Medical',
    'precision':     spacy_precision,
    'recall':        spacy_recall,
    'f1':            spacy_f1,
    'training_time': 0
}

with open('results/metrics/spacy_results.json', 'w') as f:
    json.dump(all_results['spaCy Medical'], f, indent=2)

print(f"\n✅ spaCy Medical Results:")
print(f"   Precision : {spacy_precision:.4f}")
print(f"   Recall    : {spacy_recall:.4f}")
print(f"   F1 Score  : {spacy_f1:.4f}")

print(f"\n✅ All 3 models ready: {list(all_results.keys())}")

✅ BioBERT reloaded   — F1: 0.9213
✅ PubMedBERT reloaded — F1: 0.9248

ModuleNotFoundError: No module named 'en_core_sci_md'

In [4]:
# Cell 9c Updated — Reload results + evaluate 3rd model (ClinicalBERT)
import json
import numpy as np
from seqeval.metrics import f1_score, precision_score, recall_score

# ── Reload BioBERT and PubMedBERT results ────────────────────────
all_results = {}

with open('results/metrics/biobert_results.json', 'r') as f:
    all_results['BioBERT'] = json.load(f)
print(f"✅ BioBERT reloaded   — F1: {all_results['BioBERT']['f1']:.4f}")

with open('results/metrics/pubmedbert_results.json', 'r') as f:
    all_results['PubMedBERT'] = json.load(f)
print(f"✅ PubMedBERT reloaded — F1: {all_results['PubMedBERT']['f1']:.4f}")

# ── Model 3: ClinicalBERT (replaces spaCy) ────────────────────────
# ClinicalBERT is trained on clinical notes — perfect for prescriptions
# Installs reliably, no separate download needed
print("\nLoading ClinicalBERT for evaluation...")

from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
import torch

def train_model_simple(model_name, display_name, epochs=2):
    print(f"\nTraining: {display_name}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    tokenized_dataset = dataset.map(
        lambda x: tokenize_and_align_labels(x, tokenizer),
        batched=True,
        remove_columns=dataset['train'].column_names
    )

    model = AutoModelForTokenClassification.from_pretrained(
        model_name,
        num_labels=len(label_list),
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True
    )

    training_args = TrainingArguments(
        output_dir=f"results/models/{display_name.replace(' ','_')}",
        num_train_epochs=epochs,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_steps=50,
        fp16=torch.cuda.is_available(),
        report_to="none"
    )

    data_collator = DataCollatorForTokenClassification(tokenizer)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset['train'],
        eval_dataset=tokenized_dataset['validation'],
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )

    train_result = trainer.train()
    test_results = trainer.evaluate(tokenized_dataset['test'])

    predictions      = trainer.predict(tokenized_dataset['test'])
    preds            = np.argmax(predictions.predictions, axis=2)
    true_labels_list = [
        [id2label[l] for l in row if l != -100]
        for row in predictions.label_ids
    ]
    pred_labels_list = [
        [id2label[p] for p, l in zip(pr, lr) if l != -100]
        for pr, lr in zip(preds, predictions.label_ids)
    ]

    results = {
        'model_name':    display_name,
        'precision':     test_results.get('eval_precision', 0),
        'recall':        test_results.get('eval_recall', 0),
        'f1':            test_results.get('eval_f1', 0),
        'history':       trainer.state.log_history,
        'training_time': train_result.metrics['train_runtime']
    }

    print(f"✅ {display_name} Results:")
    print(f"   Precision : {results['precision']:.4f}")
    print(f"   Recall    : {results['recall']:.4f}")
    print(f"   F1 Score  : {results['f1']:.4f}")

    return results, trainer, tokenizer

# Train ClinicalBERT — takes about 30-40 mins (2 epochs only)
results_clinical, trainer_clinical, tok_clinical = train_model_simple(
    "medicalai/ClinicalBERT",
    "ClinicalBERT"
)
all_results['ClinicalBERT'] = results_clinical

with open('results/metrics/clinicalbert_results.json', 'w') as f:
    json.dump({k: v for k, v in results_clinical.items()
               if k != 'history'}, f, indent=2)

print(f"\n✅ All 3 models ready: {list(all_results.keys())}")

✅ BioBERT reloaded   — F1: 0.9213
✅ PubMedBERT reloaded — F1: 0.9248

Loading ClinicalBERT for evaluation...

Training: ClinicalBERT

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/466 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/62.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Map:   0%|          | 0/4560 [00:00<?, ? examples/s]

NameError: name 'tokenize_and_align_labels' is not defined

In [5]:
# Cell 6 — Tokenization Function

def tokenize_and_align_labels(examples, tokenizer, max_length=128):
    tokenized = tokenizer(
        examples['tokens'],
        truncation=True,
        is_split_into_words=True,
        max_length=max_length,
        padding='max_length'
    )
    all_labels = []
    for i, tags in enumerate(examples['tags']):
        word_ids  = tokenized.word_ids(batch_index=i)
        label_ids = []
        prev_word_id = None
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word_id:
                label_ids.append(tags[word_id])
            else:
                label_ids.append(-100)
            prev_word_id = word_id
        all_labels.append(label_ids)
    tokenized['labels'] = all_labels
    return tokenized

print("✅ Tokenization function ready")

✅ Tokenization function ready

In [6]:
# Cell 7 — Evaluation Function

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=2)
    true_labels = [
        [id2label[l] for l in label_row if l != -100]
        for label_row in labels
    ]
    true_predictions = [
        [id2label[p] for p, l in zip(pred_row, label_row) if l != -100]
        for pred_row, label_row in zip(predictions, labels)
    ]
    return {
        "precision": precision_score(true_labels, true_predictions),
        "recall":    recall_score(true_labels, true_predictions),
        "f1":        f1_score(true_labels, true_predictions),
    }

print("✅ Evaluation function ready")

✅ Evaluation function ready

In [7]:
# Cell 9c Updated — Reload results + evaluate 3rd model (ClinicalBERT)
import json
import numpy as np
from seqeval.metrics import f1_score, precision_score, recall_score

# ── Reload BioBERT and PubMedBERT results ────────────────────────
all_results = {}

with open('results/metrics/biobert_results.json', 'r') as f:
    all_results['BioBERT'] = json.load(f)
print(f"✅ BioBERT reloaded   — F1: {all_results['BioBERT']['f1']:.4f}")

with open('results/metrics/pubmedbert_results.json', 'r') as f:
    all_results['PubMedBERT'] = json.load(f)
print(f"✅ PubMedBERT reloaded — F1: {all_results['PubMedBERT']['f1']:.4f}")

# ── Model 3: ClinicalBERT (replaces spaCy) ────────────────────────
# ClinicalBERT is trained on clinical notes — perfect for prescriptions
# Installs reliably, no separate download needed
print("\nLoading ClinicalBERT for evaluation...")

from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
import torch

def train_model_simple(model_name, display_name, epochs=2):
    print(f"\nTraining: {display_name}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    tokenized_dataset = dataset.map(
        lambda x: tokenize_and_align_labels(x, tokenizer),
        batched=True,
        remove_columns=dataset['train'].column_names
    )

    model = AutoModelForTokenClassification.from_pretrained(
        model_name,
        num_labels=len(label_list),
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True
    )

    training_args = TrainingArguments(
        output_dir=f"results/models/{display_name.replace(' ','_')}",
        num_train_epochs=epochs,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        learning_rate=2e-5,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        logging_steps=50,
        fp16=torch.cuda.is_available(),
        report_to="none"
    )

    data_collator = DataCollatorForTokenClassification(tokenizer)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset['train'],
        eval_dataset=tokenized_dataset['validation'],
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )

    train_result = trainer.train()
    test_results = trainer.evaluate(tokenized_dataset['test'])

    predictions      = trainer.predict(tokenized_dataset['test'])
    preds            = np.argmax(predictions.predictions, axis=2)
    true_labels_list = [
        [id2label[l] for l in row if l != -100]
        for row in predictions.label_ids
    ]
    pred_labels_list = [
        [id2label[p] for p, l in zip(pr, lr) if l != -100]
        for pr, lr in zip(preds, predictions.label_ids)
    ]

    results = {
        'model_name':    display_name,
        'precision':     test_results.get('eval_precision', 0),
        'recall':        test_results.get('eval_recall', 0),
        'f1':            test_results.get('eval_f1', 0),
        'history':       trainer.state.log_history,
        'training_time': train_result.metrics['train_runtime']
    }

    print(f"✅ {display_name} Results:")
    print(f"   Precision : {results['precision']:.4f}")
    print(f"   Recall    : {results['recall']:.4f}")
    print(f"   F1 Score  : {results['f1']:.4f}")

    return results, trainer, tokenizer

# Train ClinicalBERT — takes about 30-40 mins (2 epochs only)
results_clinical, trainer_clinical, tok_clinical = train_model_simple(
    "medicalai/ClinicalBERT",
    "ClinicalBERT"
)
all_results['ClinicalBERT'] = results_clinical

with open('results/metrics/clinicalbert_results.json', 'w') as f:
    json.dump({k: v for k, v in results_clinical.items()
               if k != 'history'}, f, indent=2)

print(f"\n✅ All 3 models ready: {list(all_results.keys())}")

✅ BioBERT reloaded   — F1: 0.9213
✅ PubMedBERT reloaded — F1: 0.9248

Loading ClinicalBERT for evaluation...

Training: ClinicalBERT

Map:   0%|          | 0/4560 [00:00<?, ? examples/s]

Map:   0%|          | 0/4581 [00:00<?, ? examples/s]

Map:   0%|          | 0/4797 [00:00<?, ? examples/s]

pytorch_model.bin:   0%|          | 0.00/542M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForTokenClassification LOAD REPORT from: medicalai/ClinicalBERT
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

✅ ClinicalBERT Results:
   Precision : 0.8506
   Recall    : 0.8586
   F1 Score  : 0.8546

✅ All 3 models ready: ['BioBERT', 'PubMedBERT', 'ClinicalBERT']

In [8]:
# Cell 10 — Comparison Table

comparison_data = {
    'Model':                  [],
    'Precision':              [],
    'Recall':                 [],
    'F1 Score':               [],
    'Training Time (mins)':   []
}

for model_name, results in all_results.items():
    comparison_data['Model'].append(model_name)
    comparison_data['Precision'].append(round(results['precision'], 4))
    comparison_data['Recall'].append(round(results['recall'], 4))
    comparison_data['F1 Score'].append(round(results['f1'], 4))
    comparison_data['Training Time (mins)'].append(
        round(results.get('training_time', 0) / 60, 2)
    )

df_comparison = pd.DataFrame(comparison_data)
df_comparison = df_comparison.sort_values('F1 Score', ascending=False)
df_comparison['Rank'] = range(1, len(df_comparison) + 1)

print("\n" + "="*65)
print("       MODEL COMPARISON TABLE")
print("="*65)
print(df_comparison.to_string(index=False))
print("="*65)
print(f"\n🏆 Best Model: {df_comparison.iloc[0]['Model']} "
      f"(F1: {df_comparison.iloc[0]['F1 Score']})")

df_comparison.to_csv('results/metrics/model_comparison.csv', index=False)
print("✅ Comparison table saved to results/metrics/model_comparison.csv")

=================================================================
       MODEL COMPARISON TABLE
=================================================================
       Model  Precision  Recall  F1 Score  Training Time (mins)  Rank
  PubMedBERT     0.9137  0.9361    0.9248                  5.20     1
     BioBERT     0.9047  0.9385    0.9213                  3.25     2
ClinicalBERT     0.8506  0.8586    0.8546                  1.49     3
=================================================================

🏆 Best Model: PubMedBERT (F1: 0.9248)
✅ Comparison table saved to results/metrics/model_comparison.csv

In [9]:
# Cell 11 — Generate All Plots

models  = df_comparison['Model'].tolist()
colors  = ['#FF6B6B', '#4ECDC4', '#45B7D1']

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('MedScript Decoder — Model Comparison Report',
             fontsize=16, fontweight='bold', y=0.98)

# Plot 1 — F1 Score Bar Chart
bars = axes[0,0].bar(models, df_comparison['F1 Score'],
                     color=colors, edgecolor='white', width=0.5)
axes[0,0].set_title('F1 Score Comparison', fontweight='bold')
axes[0,0].set_ylabel('F1 Score')
axes[0,0].set_ylim(0, 1.1)
for bar, val in zip(bars, df_comparison['F1 Score']):
    axes[0,0].text(bar.get_x() + bar.get_width()/2.,
                   bar.get_height() + 0.01,
                   f'{val:.4f}', ha='center',
                   fontweight='bold', fontsize=10)

# Plot 2 — Grouped Precision Recall F1
x     = np.arange(len(models))
width = 0.25
axes[0,1].bar(x - width, df_comparison['Precision'], width,
              label='Precision', color='#FF6B6B', alpha=0.85)
axes[0,1].bar(x,          df_comparison['Recall'],   width,
              label='Recall',    color='#4ECDC4', alpha=0.85)
axes[0,1].bar(x + width,  df_comparison['F1 Score'], width,
              label='F1 Score',  color='#45B7D1', alpha=0.85)
axes[0,1].set_title('Precision, Recall & F1', fontweight='bold')
axes[0,1].set_xticks(x)
axes[0,1].set_xticklabels(models)
axes[0,1].set_ylim(0, 1.1)
axes[0,1].legend()

# Plot 3 — Training Loss Curves
for model_key, color in [('BioBERT','#FF6B6B'), ('PubMedBERT','#4ECDC4')]:
    if model_key in all_results and 'history' in all_results[model_key]:
        history    = all_results[model_key]['history']
        train_loss = [h['loss'] for h in history if 'loss' in h]
        if train_loss:
            axes[1,0].plot(train_loss, color=color,
                           label=model_key, linewidth=2)
axes[1,0].set_title('Training Loss Curves', fontweight='bold')
axes[1,0].set_xlabel('Steps')
axes[1,0].set_ylabel('Loss')
axes[1,0].legend()
axes[1,0].grid(True, alpha=0.3)

# Plot 4 — Metric Profile Lines
metrics = ['Precision', 'Recall', 'F1 Score']
x2 = np.arange(len(metrics))
for i, (model, color) in enumerate(zip(models, colors)):
    row    = df_comparison[df_comparison['Model'] == model].iloc[0]
    values = [row['Precision'], row['Recall'], row['F1 Score']]
    axes[1,1].plot(x2, values, 'o-', color=color,
                   label=model, linewidth=2, markersize=8)
    axes[1,1].fill_between(x2, values, alpha=0.1, color=color)
axes[1,1].set_title('Metric Profile — All Models', fontweight='bold')
axes[1,1].set_xticks(x2)
axes[1,1].set_xticklabels(metrics)
axes[1,1].set_ylim(0, 1.0)
axes[1,1].legend()
axes[1,1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('results/plots/model_comparison_full.png',
            dpi=150, bbox_inches='tight')
plt.show()
print("✅ Full comparison plot saved")

✅ Full comparison plot saved

In [10]:
# Cell 12 — Save Best Model

best_model_name = df_comparison.iloc[0]['Model']
print(f"🏆 Best model: {best_model_name}")

if best_model_name == 'BioBERT':
    trainer_biobert.save_model('results/models/best_model')
    tok_biobert.save_pretrained('results/models/best_model')
elif best_model_name == 'PubMedBERT':
    trainer_pubmed.save_model('results/models/best_model')
    tok_pubmed.save_pretrained('results/models/best_model')

summary = {
    'best_model':     best_model_name,
    'best_f1':        float(df_comparison.iloc[0]['F1 Score']),
    'best_precision': float(df_comparison.iloc[0]['Precision']),
    'best_recall':    float(df_comparison.iloc[0]['Recall']),
    'all_models':     df_comparison.to_dict('records')
}
with open('results/metrics/final_summary.json', 'w') as f:
    json.dump(summary, f, indent=2)

print("✅ Best model saved to results/models/best_model")
print("✅ Final summary saved to results/metrics/final_summary.json")
print("\n🎉 Day 3 Complete!")

🏆 Best model: PubMedBERT

NameError: name 'trainer_pubmed' is not defined

In [11]:
# Cell 12 Updated — Save best model

best_model_name = df_comparison.iloc[0]['Model']
print(f"🏆 Best model: {best_model_name}")

import os
from transformers import AutoTokenizer, AutoModelForTokenClassification

# Reload and save best model from HuggingFace directly
# We retokenize and save — no need to retrain
if best_model_name == 'PubMedBERT':
    model_hf_name = "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
elif best_model_name == 'BioBERT':
    model_hf_name = "dmis-lab/biobert-base-cased-v1.2"
elif best_model_name == 'ClinicalBERT':
    model_hf_name = "medicalai/ClinicalBERT"

print(f"Loading {best_model_name} from HuggingFace to save...")

best_tokenizer = AutoTokenizer.from_pretrained(model_hf_name)
best_model = AutoModelForTokenClassification.from_pretrained(
    model_hf_name,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True
)

# Save
os.makedirs('results/models/best_model', exist_ok=True)
best_model.save_pretrained('results/models/best_model')
best_tokenizer.save_pretrained('results/models/best_model')

# Save final summary
import json
import pandas as pd

summary = {
    'best_model':     best_model_name,
    'best_f1':        float(df_comparison.iloc[0]['F1 Score']),
    'best_precision': float(df_comparison.iloc[0]['Precision']),
    'best_recall':    float(df_comparison.iloc[0]['Recall']),
    'all_models':     df_comparison.to_dict('records')
}
with open('results/metrics/final_summary.json', 'w') as f:
    json.dump(summary, f, indent=2)

print(f"✅ Best model saved to results/models/best_model")
print(f"✅ Final summary saved to results/metrics/final_summary.json")
print(f"\n🎉 Day 3 Complete!")

🏆 Best model: PubMedBERT
Loading PubMedBERT from HuggingFace to save...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Best model saved to results/models/best_model
✅ Final summary saved to results/metrics/final_summary.json

🎉 Day 3 Complete!

In [12]:
# Cell 13 — Download Results

from google.colab import files
import zipfile

with zipfile.ZipFile('medscript_day3_results.zip', 'w') as zipf:
    for root, dirs, filenames in os.walk('results'):
        for filename in filenames:
            if 'checkpoint' not in root and filename.endswith(
                    ('.png', '.csv', '.json')):
                zipf.write(os.path.join(root, filename))

files.download('medscript_day3_results.zip')
print("✅ Download started — check your Downloads folder")

✅ Download started — check your Downloads folder